### ISSUE TITLE
feature request, solid round stroke color

### ISSUE THREAD

**Issue by gcmartijn** [vladimirgamalyan/fontbm#10]
H!,

Are you going to build solid round border function in it, in the near future ?
Say for example, a white text, and a [n.n] 'px' black border.

Like this program  https://www.71squared.com/glyphdesigner , https://www.bmglyph.com

**Comment by vladimirgamalyan** [comment]
Hi!, sorry, there are no such plans in the near future. Anyway, PRs are welcome!
