### ISSUE TITLE
Glyph quality?

### ISSUE THREAD

**Issue by 0xDC00** [vladimirgamalyan/fontbm#12]
![image](https://user-images.githubusercontent.com/29352751/116977640-e0e07d80-acec-11eb-9db6-e2b523f15e82.png)
fontbm vs notepad vs hiero.

Glyph rendered, not good as Hiero (freetype).
Please take a look,
Chars: Ẳ Ầ Ặ Ẫ Ấ Ắ

---
![image](https://user-images.githubusercontent.com/29352751/116976965-0b7e0680-acec-11eb-9a0b-6775fda6ea6d.png)
fontbm vs bmfont
Baseline still not correct (char: g): https://github.com/vladimirgamalyan/fontbm/issues/8

**Comment by vladimirgamalyan** [comment]
@0xDC00  can you share the arial.ttf and the command line used for generate the font (can't reproduce on my arial.ttf).

**Comment by 0xDC00** [comment]
@vladimirgamalyan Hi,

arial.ttf: <https://drive.google.com/file/d/17DUIDIneeQRCj_daqJEZjqZGz0Cyg0TI/view?usp=sharing>
command: `fontbm --font-size 48 --texture-width 512 --texture-height 384 --data-format txt --include-kerning-pairs --chars-file "chars.txt" --font-file arial.ttf --output arial`
chars.txt: `A Á Â Ấ Ắ Ễ Ỗ`

Sorry for the late reply, please check.

**Comment by vladimirgamalyan** [comment]
I've got it, hiero (and also SFML) uses FT_LOAD_FORCE_AUTOHINT flag to force FreeType hinting module instead font's native hinter (which produces not so good result in our case).
I've added the same flag to last [Release](https://github.com/vladimirgamalyan/fontbm/releases/tag/v0.4.2), it should fix the issue.

**Comment by 0xDC00** [comment]
Look better now, thanks.
