### ISSUE TITLE
Feature: glyph alignment

### ISSUE THREAD

**Issue by phoddie** [vladimirgamalyan/fontbm#19]
Moddable is experimenting with a GPU that is more efficient when the x coordinate of a glyph is an even number. I couldn't find a way to achieve this with the existing command line options of fontbm. As a quick experiment, I changed [line 19 of App.cpp](https://github.com/vladimirgamalyan/fontbm/blob/e7d46c174cfaf9004c711e4b8109f768fcbdc013/src/App.cpp#L19) `App::getGlyphRectangles` to round with glyph width:

```
result.emplace_back(((glyphInfo.width + additionalWidth) + 1) & ~1, glyphInfo.height + additionalHeight, kv.first);
```

This succeeds in forcing all the glyphs to an even horizontal position. Perhaps this could be an option like `--align-horiz=2` and `--align-vert=10`. The default would be `1` to maintain the current behavior.

I am willing to try to make the changes, but first want to check if the approach is reasonable and you are willing to consider the feature. Thank you.

**Comment by vladimirgamalyan** [comment]
I don't think it will be useless, so I'm in.
BTW, does the GPU also require even width? I know some GPU likes 32-bit aligned addresses, but never heard about even numbers.
It would be nice to cover more cases, so I'd like more info how the GPU uses font textures.

**Comment by phoddie** [comment]
Closing this issue as the PR to implement it has been merged. (Thank you!)
