### ISSUE TITLE
fontsize value is negative

### ISSUE THREAD

**Issue by NworbLegin** [vladimirgamalyan/fontbm#24]
I'm not sure why the fontsize value that you write to the output file is negative, when this should be positive integer.

(first line of text format .fnt file)
`info face="Noto Sans" size=-48 bold=0 italic=0 charset="" unicode=1 stretchH=100 smooth=0 aa=1 padding=2,2,2,2 spacing=0,0 outline=0`

Command line input has
`fontbm.exe --font-file NotoSans-Regular.ttf --output notosans --chars 0-0,32-126,160,163,169,180,183,225,231,233,697-701,714-715,748,750,756-758,8210-8213,8216-8217,8220,8221,8471 --chars-file charsfile_pronunciation.txt --padding-left 2 --padding-right 2 --padding-up 2 --padding-down 2 --font-size 48 --texture-size 256x256,512x512,1024x512,1024x1024 --data-format txt`

It looks like you set the value on line 257 of App.cpp as follows:

`    f.info.size = -static_cast<std::int16_t>(config.fontSize);`

but I think you should not be negating the value from config.fontSize

instead it should be

`    f.info.size = static_cast<std::int16_t>(config.fontSize);`

This is coming through as a negative value both in the txt format output and the bin format output (probably others as well). We use the binary value for our projects.

Cheers

Nigel

**Comment by NworbLegin** [comment]
PR #25

**Comment by vladimirgamalyan** [comment]
Yep, it made intentionally for [bmfont](https://www.angelcode.com/products/bmfont/) compatibility, when the "Match char height" checked in their Font Setting dialog, the font Height value becomes negative. You can find `fontSize = -fontSize;` at http://svn.code.sf.net/p/bmfont/code/trunk/source/choosefont.cpp

**Comment by NworbLegin** [comment]
Ah. The joys of undocumented parameters in the original BM font format. We don't normally have "Match char height" selected for our fonts so we wouldn't have seen this before. Apologies.
