### ISSUE TITLE
Request: Compiled Version

### ISSUE THREAD

**Issue by bikasx** [vladimirgamalyan/fontbm#3]
This seems like a great tool, however i have no idea how to actually use it.

Does compiled version exist somewhere?

Thanks.

**Comment by vladimirgamalyan** [comment]
Yeah, it is possible now. Grab the binaries from [Releases](https://github.com/vladimirgamalyan/fontbm/releases) page (`fontbm.zip` for windows, include all required .dll, or `fontbm` for linux).
