### ISSUE TITLE
Some kerning missing

### ISSUE THREAD

**Issue by htdag** [vladimirgamalyan/fontbm#4]
TTF vs BMFont vs FontBM (ươ ượ VA ...).
From image, bitmap font from fontbm with `--include-kerning-pairs` but kerning amount is wrong.
![TTF with BMFont and FontBM](https://i.imgur.com/Oy8Avme.png)

**Comment by vladimirgamalyan** [comment]
Nice catch! Can you share your command line and font and then I could reproduce the problem.

**Comment by htdag** [comment]
`fontbm --font-file sample.ttf --output sample --font-size 48 --texture-width 512 --texture-height 384 --data-format xml --include-kerning-pairs --chars-file "chars.txt"`

[sample.zip](https://drive.google.com/uc?id=1zLUZdMJbpFbDM0QPfbcqGyCCz1LqXF2j&export=download)

**Comment by vladimirgamalyan** [comment]
Just fixed missing kernings, there was only one kerning value for each pair of characters (for example for `A` and `V`, but not for `V` and `A`).
