### ISSUE TITLE
TTF embedded bitmaps handled incorrectly

### ISSUE THREAD

**Issue by cherniid** [vladimirgamalyan/fontbm#5]
Some TTF fonts, for example Terminus TTF (https://files.ax86.net/terminus-ttf/), embed bitmaps for several font sizes. Freetype correctly loads these bitmaps when asked in FT_Load_Char - but in monochrome format (bitmap.num_grays = 2, bitmap.pixel_mode == FT_PIXEL_MODE_MONO), so you need to check and unpack monochrome bits to 8-bit grayscale bytes first before mixin in 4-byte color and alpha.

**Comment by cherniid** [comment]
fixed in https://github.com/vladimirgamalyan/fontbm/pull/6

**Comment by vladimirgamalyan** [comment]
Cool! Thank you! Will merge in a minute.
