### ISSUE TITLE
Mac version?

### ISSUE THREAD

**Issue by phoddie** [vladimirgamalyan/fontbm#9]
This isn't a bug report but a question. If here's a better place to post it, please let me know.

Your `fontbm` tool looks great. The rectangle packing is particularly impressive. We use BMFonts in the [Moddable SDK](https://github.com/Moddable-OpenSource/moddable) to render anti-aliased text on a variety of microcontrollers. Our graphics documentation provides [details](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/commodetto/commodetto.md#bmfont) about the  features we use.

To generate BMFonts we usually use [Glyph Designer](https://www.71squared.com/glyphdesigner), which is excellent but only available for macOS. We would like to have a single tool that works  on all our development environments - macOS, Windows, and Linux. That way we can provide developers with consistent instructions and build integration no matter what  platform they develop on.

One member of our community has already [been successful](https://github.com/Moddable-OpenSource/moddable/issues/325#issuecomment-763472496) using `fontbm`with the Moddable SDK on Windows. 

So... I wanted to ask if you had plans to support macOS at some point down the road.

Thank you!

**Comment by vladimirgamalyan** [comment]
Hi! Sorry for the late reply =)
Afaik, `cmake . / make` should be enough for macOS build, at least Travis builds it right (https://travis-ci.org/github/vladimirgamalyan/fontbm/jobs/759773086). Unfortunately I don't have access to macOS to check it by myself, but I believe that there are great chances that everything will be ok :santa:.

**Comment by phoddie** [comment]
Hey, @vladimirgamalyan  - thanks for the reply. @andycarle [independently found](https://github.com/Moddable-OpenSource/moddable/issues/325#issuecomment-769615337) that what you propose works well on macOS! Very cool. Maybe you can update your build instructions to note that the Linux instructions work for macOS as well.

We are looking at ways we can integrate your `fontbm` tool into our Moddable SDK build system to automatically generate bitmap fonts at the sizes needed by the project.
